apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tcog-frontend-ingress
  labels:
    app: tcog-frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: "16m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    # 启用gzip压缩
    nginx.ingress.kubernetes.io/enable-gzip: "true"
    # 缓存配置
    nginx.ingress.kubernetes.io/configuration-snippet: |
      location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
      }
      location /csv/ {
        expires 1h;
        add_header Cache-Control "public";
      }
      location /dist/ {
        expires 1h;
        add_header Cache-Control "public";
      }
spec:
  ingressClassName: nginx
  rules:
  - host: tcog-game.local  # 可以根据实际域名修改
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tcog-frontend
            port:
              number: 80
  # 如果需要HTTPS，可以添加tls配置
  # tls:
  # - hosts:
  #   - tcog-game.local
  #   secretName: tcog-frontend-tls 